### ISSUE TITLE
uploadProgress Android

### ISSUE THREAD

**Issue by allvintage** [wkh237/react-native-fetch-blob#120]
Hi,

thank you for this awesome project. I'm having trouble with uploadProgress on Android and couldn't find any solutions in Issues or Wiki. On iOS everything is working fine, but on Android it seems as if the uploadProgress Handler is completely being ignored.

I'm using this code to make a request to my server:

RNFetchBlob.fetch('POST', 'https://www.example.com', {
    'Content-Type' : 'application/json'
}, JSON.stringify({myObject}))

// listen to upload progress event
.uploadProgress((written, total) => {
    console.log('uploaded', written / total)
})

// listen to download progress event
.progress((received, total) => {
    console.log('progress', received / total)
})

.then((response) => response.json())
.then((responseData) => {
    console.log(responseData);
})

.catch((err) => {
    console.log(err);
});
Some information that might or might not be useful:

myObject contains all necessary information to authenticate on my remote server www.example.com (which returns JSON responses) and also includes rather large base64 encoded images. Because of this uploading can take a while, therefore I want to implement an upload progress indicator.

Again, on iOS everything works like a charm. On Android the uploadProgress event handler is not even being called. The download progress event handler works fine on Android and iOS. I'm running the app without simulators on an Android Nexus Phone and iPhone 6s directly.

What am I missing?

Thank you in advance for your help!

**Comment by wkh237** [comment]
@allvintage , thank you for reporting this issue. I think this due to you're uploading the body `as-is`, in this case our Android network module reads the whole data into request body instead of using byte stream, therefore it won't trigger upload progress event. 

I think it's reasonable to change the design so that the behavior is more consistent with IOS. However, there's a workaround, you can try to convert the data to BASE64 string before sending it, and append `;BASE64` to `Content-Type`, I think it might work 😄 

```js
let dataStr = JSON.stringify({myObject})
RNFetchBlob.fetch('POST', 'https://www.example.com', {
'Content-Type' : 'application/json;BASE64'
}, RNFetchBlob.base64.encode(dataStr))
```

I'll add this into next `beta` release, thank you !!

**Comment by wkh237** [comment]
I've published a `beta` version to npm, please try upgrade the package

```
$ rnpm install react-native-fetch-blob@beta
```

**Comment by allvintage** [comment]
Wow, you're fast! 👍 I was just changing my PHP to decode base64, but now it works without a single line of code change. Thank you so much!
