### ISSUE TITLE
console.warn('finished request could not be canceled')

### ISSUE THREAD

**Issue by jo2010** [wkh237/react-native-fetch-blob#121]
This is so weird, only on iOS during facebook sign with firebase, this warning is thrown, and firebase facebook sign is not working. Works fine in android. When I look at the call stack I se index.js and XMLHTTPRequest from react-native-fetch-blob. Why react-native-fetch-blob code getting called during Facbook Firebase auth?

**Comment by wkh237** [comment]
Hi @jo2010 , thanks for the information. 

Once you replaced window.XMLHttpRequest with our implementation it's reasonable RNFB got called because these libraries sending HTTP request base on window.XMLHttpRequest.

The Web API polyfills are still in experimental so if you're using `0.9.3` or earlier version, I'd recommend you try install latest `beta` version and see if the problem got solved.

```sh
$ rnpm install react-native-fetch-blob@beta
```

You can turn on logs of XMLHttpRequest and Blob polyfill to see what are the request and response by change [this line](https://github.com/wkh237/react-native-fetch-blob/blob/master/src/polyfill/XMLHttpRequest.js#L14)

```js
-log.disable()                                                                                                                                                                                                    
+log.level(3)                                                                                                                                                                                                    
```

if you're using `beta` releases, there's a static method [setLog()](https://github.com/wkh237/react-native-fetch-blob/wiki/Web-API-Polyfills-(experimental)#setloglevelnumber) to do the same thing.

**Comment by wkh237** [comment]
@jo2010 , not sure how you use FB credential with Firebase but I'm able to get it work with `0.9.4-beta.7` and `react-native-fbsdk`, looks like it's working properly on IOS. 

Here's my code 

```js

import React from 'react'
import RNFetchBlob from 'react-native-fetch-blob'
import firebase from 'firebase'
import { LoginManager, AccessToken} from 'react-native-fbsdk';

window.XMLHttpRequest = RNFetchBlob.polyfill.XMLHttpRequest
window.Blob = RNFetchBlob.polyfill.Blob

// Initialize Firebase
var config = {
  apiKey: "*****",
  authDomain: "*****.firebaseapp.com",
  databaseURL: "https://*****.firebaseio.com",
  storageBucket: "******.appspot.com",
};

firebase.initializeApp(config);
let auth = firebase.auth();
let provider = firebase.auth.FacebookAuthProvider;

LoginManager.logInWithReadPermissions(['public_profile'])
.then(loginResult => {
    if (loginResult.isCancelled) {
        console.log('user canceled');
        return;
    }
    AccessToken.getCurrentAccessToken()
    .then(accessTokenData => {
        const credential = provider.credential(accessTokenData.accessToken);
        return auth.signInWithCredential(credential);
    })
    .then(credData => {
        console.log(credData);
        // upload an image
        let testImage = `firebase-fbcred-${Platform.OS}-${Date.now()}.png`
        RNTest.prop('firebase-image', testImage)

        // create Blob from BASE64 data
        Blob.build(RNTest.prop('image'), { type : 'image/png;BASE64'})
        .then((blob) => {
          let storage = firebase.storage().ref('rnfbtest')
          let task = storage
            .child(RNTest.prop('firebase-image'))
            .put(blob, { contentType : 'image/png' })
            .then((snapshot) => {
              console.log(snapshot.metadata)
            })
        })
    })
    .catch(err => {
        console.log(err);
    });
});
```
