### ISSUE TITLE
[question] How to download xlsx file then using SheetJs to convert to workbook?

### ISSUE THREAD

**Issue by TechBK** [wkh237/react-native-fetch-blob#142]
My project need download a xlsx file and read it.
I using https://github.com/SheetJS/js-xlsx.
Plzz show to me how to do it with `react-native-fetch-blob`.

Example with ajax:

```javascipt
/* set up XMLHttpRequest */
var url = "test_files/formula_stress_test_ajax.xlsx";
var oReq = new XMLHttpRequest();
oReq.open("GET", url, true);
oReq.responseType = "arraybuffer";

oReq.onload = function(e) {
  var arraybuffer = oReq.response;

  /* convert data to binary string */
  var data = new Uint8Array(arraybuffer);
  var arr = new Array();
  for(var i = 0; i != data.length; ++i) arr[i] = String.fromCharCode(data[i]);
  var bstr = arr.join("");

  /* Call XLSX */
  var workbook = XLSX.read(bstr, {type:"binary"});

  /* DO SOMETHING WITH workbook HERE */
}

oReq.send();
```

**Comment by wkh237** [comment]
@TechBK , unfortunately I think it's not possible to make it work in RN at this moment. SheetJS uses many Web APIs that RNFB and JSC not yet implemented, such as FileReader, and Typed Array it might took lot of time to make it work. 

On the other hand, I think SheetJS there'd be some performance issue even if we make it work since it uses Typed Array extensively.
