### ISSUE TITLE
Unhandled Promise Rejection - listeners is not defined

### ISSUE THREAD

**Issue by funkysoul** [wkh237/react-native-fetch-blob#187]
I'm getting this "Warning" after successfully uploading an Image to Firebase.
I'm using the sample code provided in the example (small modifications nothing fancy, only filename and firebase location logic).

After dismissing this message I also get a further warning only in the console:
"Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'."

I'm not sure if I'm doing anything wrong or forgot a step in-between.. Many thanks for your help

RN: 0.37.0
Lib: 0.10.0

<img width="379" alt="screen shot 2016-11-17 at 09 18 08" src="https://cloud.githubusercontent.com/assets/315914/20381315/3e8adff2-aca7-11e6-904f-f965230bcf1e.png">

**Comment by wkh237** [comment]
@funkysoul , thanks for reporting the issue, I think the problem is here : 

[https://github.com/wkh237/react-native-fetch-blob/blob/master/src/polyfill/EventTarget.js#L74](https://github.com/wkh237/react-native-fetch-blob/blob/master/src/polyfill/EventTarget.js#L74)

the missing `this` before `listeners[i]`

**Comment by funkysoul** [comment]
@wkh237 indeed! warning gone.

**Comment by Pianist038801** [comment]
@wkh237 I am having the same issue. It makes me unable to do debug. What can I do right now?

**Comment by whysetiawan** [comment]
@wkh237 i am having the same issue. My library is 0.10.8 version. What should i do now?
