### ISSUE TITLE
Android runtime permissions

### ISSUE THREAD

**Issue by vince-rowe** [wkh237/react-native-fetch-blob#23]
Hi,

Android 23 runs with runtime permissions, so if you want to write to the downloads folder for example you don't just state that in the manifest file, you also have to have a runtime check and confirmation from the user. 

https://developer.android.com/training/permissions/requesting.html

I can't see that how this has been implemented in this module, if it hasn't due to being outside of scope / requirements then does anyone have any advice on how to apply this. Due to the nature of the module here I would think it would be very useful to add to the Read me.

Thanks

**Comment by wkh237** [comment]
Hi @vince-rowe , great thanks for informing! I've considered for a while, this problem will become more and more general for RN developers since the mechanism will finally become a standard in mainstream Android devices, and some unified solution may appear (perhaps it will finally become part of official API). Therefore I do not tend to implement the feature in this module.

But It is necessary to inform the developers in README, and suggest them head for solutions such as [react-native-android-permission](https://github.com/lucasferreira/react-native-android-permissions).

**Comment by vince-rowe** [comment]
Hi,

That all makes sense. The solution you linked to works as planned and integrates well, so yep a simple README update would be great for future reference.

Thanks

**Comment by wkh237** [comment]
Great 👍, I've updated the README in [this commit](https://github.com/wkh237/react-native-fetch-blob/commit/fd5900ca112e58bfeaedfc5eb2e82d5e8bf8ef2b).
