### ISSUE TITLE
readStream Crash

### ISSUE THREAD

**Issue by naviocean** [wkh237/react-native-fetch-blob#247]
Hello,
I got an issue that when I tried to set encoded to utf8, readStream method is crashed.
```
RNFetchBlob.fs.readStream(image.uri,'utf8').then(stream=>{
                      stream.open();
                      stream.onData((chunk)=>{
                     
                      })
                    })
```
Im using 0.10.2-beta.8
Thanks

**Comment by wkh237** [comment]
@naviocean , this error is due to that RCTEventEmitter could not convert JSON strings containing invalid UTF8 characters, I'm afraid this is beyond scope, but I can add exception handling so that it will not crash when dealing with such kind of files. 

Alternatively it's possible to use `ascii` encoding to get byte array of the image, and deal with the bytes, but it has performance drawback especially when the file is large.
