### ISSUE TITLE
[iOS] Strange lastModified received from RNFB.fs.stat

### ISSUE THREAD

**Issue by Meshz** [wkh237/react-native-fetch-blob#254]
@wkh237 Hello, I'm receiving a strange timestamp for `lastModified` when using RNFB.fs.stat on a saved file on iOS. Here's the output of the response:

```
{
    type: 'file',
    filename: '.picture.jpg',
    size: '86766',
    path: '/var/mobile/Containers/Data/Application/EFB8FD2B-B6E1-4DE6-8EB9-959993D455D6/Documents/AppName/.picture.jpg',
    lastModified: 407828584
}
```

Any idea what's going on? Thanks for help!

**Comment by Slooowpoke** [comment]
Strange as in because its numerical? Or strange because its not working?
It returns a epoch (unix timestamp), but I assume you already know that.
That is an odd date, I can confirm that I'm also receiving odd timestamps. Even with this fix: https://github.com/wkh237/react-native-fetch-blob/commit/5c20ca66a3381ad0e660344f33e86fe2bb33d637

**Comment by Meshz** [comment]
I mean strange because the returned TS doesn't match the datetime I created the file.
Unless I created it on 1982-12-04 06:43:04 but it's not the case. XD

**Comment by Slooowpoke** [comment]
I thought that was what you meant, but just had to be sure ;D

I can get a timeInterval with the following (which returns the correct timestamp), but I think my JS is a bit squiffy and converting it wrongly.

```    
NSDate * lastModified = [info fileModificationDate];
NSTimeInterval ti = [lastModified timeIntervalSince1970];
```

**Comment by Meshz** [comment]
@Slooowpoke I just tried your fix and it is working now. I can't say why the *1000 in native code breaks the TS because I'm not familiar with Objective-C. Do you plan to make a PR or waiting for an enlightenment on the native *1000 problem? Thank you for your help. 👍

**Comment by Slooowpoke** [comment]
Glad it helped! I think I'm going to wait it out for someone who knows more about it, otherwise if I pick up enough Objective-C on the way I'll make one. 

I read some stuff on the way about double casting a long `(long long)` but none of that seemed to yield results, I need to know more Objective-C syntax as well. >.<
