### ISSUE TITLE
how to stop download

### ISSUE THREAD

**Issue by budingts** [wkh237/react-native-fetch-blob#256]
when the download is starting,how to stop download

**Comment by wkh237** [comment]
@juanq123 , please refer to our [wiki](https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API)

**Comment by juanq123** [comment]
![aaa](https://cloud.githubusercontent.com/assets/5056373/22729448/bbebcb20-ee1d-11e6-8239-2790d54bb6f0.png)
 I use like this，but 

“this.task.cannel is not a function”

**Comment by wkh237** [comment]
@juanq123 , try to separate the statement into lines like this and see if it works

```js
download() {
  this.task = RNFetchBlob.config(...).fetch()
  this.task.progress(...)
  this.task.then(...)
}

stop() {
  this.task.cancel()
}
```

**Comment by bhuizi** [comment]
@budingts 

This issue is that the .fetch() is in a different scope and that .cancel() needs to be called on .fetch(). From the docs:
`let task = RNFetchBlob.fetch('GET', 'http://example.com/file/1')

task.then((data) => {
  // .. success
})
.catch((err) => {
  console.log(err)
})

// cancel the HTTP request
task.cancel((err, taskId) => {
  // task successfully canceled
})` 

task has already returned the .fetch() call with attached promise that will either resolve/reject which allows task to be thenable.
example being:
`class example extends Component {
   super()
   this.handleDownload = this.handleDownload.bind(this);
   this.handleCancel = this.handleCancel.bind(this);
   this.task = RNFetchBlob
     .config({fileCache : true, path : `${dirs.DocumentDir}/example-app/content.zip`})
     .fetch('GET','http://someurl.com');

    handleCancel() {
    this.task.cancel((err, taskId) => {
      console.log(`Cancel: taskId ${taskId}`);
    })
    this.setState({progressNumber: 0});
  }
  handleDownload(){
    if(!this.task.onProgress){
      this.task.progress({ interval : 100 }, (received, total) => {
        const progressNumber = Math.floor(received/total*100)/100;
        this.setState({progressNumber});
      })
      .then(res => {
          console.log(res);
      })
      .catch((errorMessage) => {
        console.log(errorMessage);
      })
    } else {
   
      console.log('no task');
    }
  }

}`

**Comment by Johncy1997** [comment]
this.task.cancel() calls .then() method.How to know the response is stopped in cancel method?
