### ISSUE TITLE
How can I stop the blob files from automatically deleting after .build callback ; React Native 

### ISSUE THREAD

**Issue by ajonno** [wkh237/react-native-fetch-blob#316]
we're using this library in a React Native project (0.41) and your version being used is 0.10.4

after this call completes successfully:
```
   Blob
     .build(rnfbURI, { type : `image/${uriImageType};`})
     .then((blob) => {
        .....

        blob.close();
     }
```

we can see the blob file being DELETED from the directory on device. However we want to keep it stored/available. We tried this before the call above but no dice.
```
   RNFetchBlob           <===added this
      .config({
        fileCache : true
   });

    let rnfbURI = RNFetchBlob.wrap(iOSTemporaryFilePathString);

```

Can you help re explaining what flag(s) we need to set to ensure the file does not get cleaned up automatically ? Many thanks.

**Comment by wkh237** [comment]
@ajonno , sorry for replying late. By design, if you create a Blob from existing file, the source file will be removed once you close the blob. We doing this because the source file might be a large one, and we're not going to make a copy of that when creating a new Blob.

However, I know this might not be a good design, people already gave us some feedback. Perhaps we can make it optional. Has any idea?

**Comment by ajonno** [comment]
no problem and thanks for getting back on this. let me have a look at the new method and test it, how it fits into the use case etc and I'll come back to you shortly.
