### ISSUE TITLE
Library doesn't compile with project on IOS

### ISSUE THREAD

**Issue by sadhwaniyash6** [wkh237/react-native-fetch-blob#41]
I get the below error message when I try to compile my project in IOS. The project works fine on android. I have followed the steps as given in the installation section. 
![screen shot 2016-07-01 at 7 15 41 pm](https://cloud.githubusercontent.com/assets/11190073/16619986/48b507b2-43ae-11e6-82d9-3bc160eb0c80.png)

**Comment by wkh237** [comment]
Hi @sadhwaniyash6 , thank you for your report. Could you try install the latest version `0.6.1` from npm ?  According to your screenshot, seems the package you've installed is not latest version the latest RNFetchBlobResp.h should look like [this](https://github.com/wkh237/react-native-fetch-blob/blob/master/src/ios/RNFetchBlobNetwork.h#L9). I believe the bug has already been fixed on `0.5.7`. This bug can also be fixed by upgrade your Xcode to version >=`7.3`, please see #31 #30 for more information. 

If the error still occurs after upgrade the package and Xcode, please let me know, thank you.

**Comment by wkh237** [comment]
Closing this Issue closed due to no response from author, besides this issue should have been fixed in previous release.
