### ISSUE TITLE
Feature: Calculate file hash (with links to source code)

### ISSUE THREAD

**Issue by lll000111** [wkh237/react-native-fetch-blob#439]
**EDIT:** See below, the topic changed. It now is a feature request.

---

I looked at react-native-fs and at this package (which we already use). I *must* save binary files - not base64 encoded (we save files under the SHA-256 of their content, and a base64 encoded binary has a completely different SHA-256 than the binary version - but then our distributed system would not recognize those files as the same).

I'm confused.

Do you know why binary always is text (base64) in React-Native? I don't get it. I don't understand programming for mobile, but I doubt Android only handles text files. Nor is Javascript limited to text files. 

So why can't I save BINARY files?

**Comment by wkh237** [comment]
Well, from my understanding it's about the way React Native communicate with `native` context. 

When you invoke a native API from javascript, the arguments must be serialized to JSON string before they sent to native, and it does similar process when the native context is returning the result to javascript context.

That's why most of the libraries use BASE64 format to represent binary data, but it does not matter because the BASE64 string will finally be decoded into binary bytes, it's just less performant. 

To be short, you **CAN** store binary data in React Native.

**Comment by lll000111** [comment]
Thanks, I'll see where this (RN stuff) will lead us and our requirements.

**Comment by lll000111** [comment]
After looking around the code and the API a bit more I have another question:

I don't see a way to calculate a crypto-hash over a binary file, because if I were to use an algorithm in Javascript I would only see the BASE64 string?

## FEATURE REQUEST

Would it be possible to include the (pretty simple) [function from react-native-fs `hash(filepath: string, algorithm: string): Promise<string>`](https://github.com/itinance/react-native-fs#hashfilepath-string-algorithm-string-promisestring)?

The Android implementation: https://github.com/itinance/react-native-fs/blob/master/android/src/main/java/com/rnfs/RNFSManager.java#L212

The iOS implementation: https://github.com/itinance/react-native-fs/blob/master/RNFSManager.m#L309

**Comment by sm2017** [comment]
@wkh237 I need these feature too , I need to SHA256 of files
