### ISSUE TITLE
Changes that slowed down download?

### ISSUE THREAD

**Issue by PimDeWitte** [wkh237/react-native-fetch-blob#48]
Hi guys,

I'm using this library to download a massive amount of separate files to disk (1k+ per load). It's a mapping application, and so this is necessary.

Since the latest version (I upgraded from 0.4.2 to 0.5.2) downloads have slowed down significantly. Any suggestions where I can look to fix this? It almost seems like the requests are now syncrhonous instead of asynchronous. Unable to perform multiple requests at the same time?

Thanks!

**Comment by wkh237** [comment]
Hi @PimDeWitte , thank you for your information, I think this is a significant issue, and I'd like to figure out what's the root cause, but I need more information. 

Does this happens on Android ? Or it's IOS only problem ? I've change the HTTP implementation since 0.5.0 the requests now handled by main thread asynchronously. Could you provide informations such as number of concurrent connections, file size, or a sample code (I think this would be helpful) 😏 . Another possible reason is that your app is updating GUI base on `progress` event since the event triggers in a very high frequency.  

You can also try the latest version `0.6.2`, because there has some changes either (but I suppose it may not make big difference 😅).

**Comment by wkh237** [comment]
@PimDeWitte , I've found possible solution, could you try install the package `0.6.3-dev.1` ? This is a version based on branch `issue_48` 

```bash
# remove package
$ rnpm unlink react-native-fetch-blob
$ npm uninstall react-native-fetch-blob
# install dev version
$ npm install --save react-native-fetch-blob@0.6.3-dev.1
$ rnpm link react-native-fetch-blob
```

I found that before applying this change, concurrent HTTP request are limited to a very small number. The commit bd92225 improved the limit number, I'm able to download 1500 files (each has about 100kb) in 40 seconds after this commit.

If this fix the problem I'll publish a new version on npm. 

Thank you!
