### ISSUE TITLE
how to createFile with 'gbk' encode

### ISSUE THREAD

**Issue by yeatsYz** [wkh237/react-native-fetch-blob#490]
in my project, I need to generate a txt file with ANSI encode type where file will be used in the windows.But the method createFile in fileSystem API doesn't support this encode.Can you support this?

**Comment by lll000111** [comment]
You can create any binary files you want, and that means you can create any files you want. Just use "ascii" (which actually means an array of values 0.225, i.e. a byte array) or base64 (much faster) instead of utf8. I don't see how this is an RNFB issue. nor do I quite understand your problem. Inside Javascript "string" is fixed by the language, and to save other formats you have the mentioned methods.

**Comment by lll000111** [comment]
Feel free to reopen if you still have a question.
