### ISSUE TITLE
How do I save a file and download it via blob data?

### ISSUE THREAD

**Issue by huangtubiao** [wkh237/react-native-fetch-blob#507]
How do I save a file and download it via blob data?

```js
const Blob = RNFetchBlob.polyfill.Blob
Blob.build(SOME_BASE64_ENCODED_DATA, { type: 'image/png;base64' })
    .then((blob) => {
        // do something with the Blob
    })
```

**Comment by lll000111** [comment]
There are examples in the Wiki:

https://github.com/wkh237/react-native-fetch-blob/wiki/Fetch-API#available-request-body-types

**Comment by huangtubiao** [comment]
@lll000111 Thank you for the reply, but these examples still can not solve my problem. My question is how to save blob as a file, it just like:

https://github.com/eligrey/FileSaver.js/

```js
var FileSaver = require('file-saver');
var blob = new Blob(["Hello, world!"], {type: "text/plain;charset=utf-8"});
FileSaver.saveAs(blob, "hello world.txt");
```

**Comment by lll000111** [comment]
If you look at the implementation (which I'm only just reading too) at

https://github.com/wkh237/react-native-fetch-blob/blob/master/polyfill/Blob.js

you can find there are methods on the Blob object such as `readBlob` in line 267 or, since Blobs already use the filesystem to store the data,  `getRNFetchBlobRef` in line 219 which returns the location of the file that holds the data of the Blob object.

**Comment by lll000111** [comment]
@abhishek71994 Please read the README

**Comment by abhishek71994** [comment]
@lll000111 I have but there is nothing informative.. Is the issue which I am referring to fixed? I read that expo doesnt support RNFB.

**Comment by lll000111** [comment]
@abhishek71994  PLEASE READ THE PROJECT README.

> wkh237's last Github activity was in September 2017, and he has not reacted to emails either. This repository no longer is the main location of "react-native-fetch-blob".

You can find the project owner and get him to come back or you can continue to write comments to `/dev/null`
