### ISSUE TITLE
Error compiling since 0.9.2

### ISSUE THREAD

**Issue by Kaishley** [wkh237/react-native-fetch-blob#97]
Hi,

I just updated to 0.9.2 and I am having the following error when compiling.

`android\src\main\java\com\RNFetchBlob\RNFetchBlobBody.java:107: error: method contentLength() is already defined in class RNFetchBlobBody
    public long contentLength() {
                ^
Note: Some input files use or override a deprecated API.`

_There's duplicated code in the RNFetchBlobBody.java at lines 97 and 107_

**Comment by wkh237** [comment]
Hi @Kaishley , thanks for reporting this issue. I think this only happens on react-native < 0.27 since the older OkHttp does not support overriding `contentLength` method. 

The reason why we override `contentLength` is addressed in #94 , therefore I think to fix this problem by change [prelink script](https://github.com/wkh237/react-native-fetch-blob/blob/master/src/scripts/prelink.js) is a much preferable way 👍

**Comment by Kaishley** [comment]
Hi @wkh237 
The problem is there is duplicate code of the override. Please check lines 97 and 107 :)

**Comment by wkh237** [comment]
Okay, @Kaishley I see the duplicated code there, I'll merge the PR, thank you 😄

**Comment by wkh237** [comment]
@Kaishley , a new version `0.9.3` is published to npm, please try to install the updated package, feel free file an issue if there's any problem, thank you 😏

**Comment by Kaishley** [comment]
@wkh237 Cheers ;)
